import Link from "next/link";
import "./../../globals.css";

export default function NativelyAlternative() {
  return (
    <>
      <main className="container section" style={{maxWidth: '800px'}}>
         <nav style={{marginBottom: '4rem'}}>
           <Link href="/" className="btn btn-secondary">&larr; Shipkraft Home</Link>
         </nav>
         
         <h1 className="hero-title" style={{fontSize: '3rem'}}>Looking for a Natively Alternative?</h1>
         
         <div style={{color: '#aaa', fontSize: '1.1rem', lineHeight: '1.8', marginTop: '3rem'}}>
            <p style={{marginBottom: '1.5rem'}}>Natively provides a solid service for converting bubble apps into mobile wrappers. However, if you are looking to take modern React Native code generated by Claude, Cursor, or Lovable and compile it into a true native APK, you need a dedicated pipeline.</p>

            <h3 style={{color: '#fff', fontSize: '1.5rem', margin: '3rem 0 1rem'}}>Shipkraft vs Natively</h3>
            <ul style={{marginBottom: '1.5rem', paddingLeft: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem'}}>
              <li><strong>Framework agnostic:</strong> Natively is heavily tied to specific no-code website builders. Shipkraft compiles bare React Native and Expo code exactly as written, offering true native performance rather than a web wrapper.</li>
              <li><strong>Shareable Browser Emulator:</strong> Shipkraft integrates with Appetize.io, providing a URL where users can interact with a virtual iPhone/Android directly in Safari or Chrome.</li>
            </ul>

            <div style={{padding: '2rem', background: '#111', border: '1px solid #333', borderRadius: '12px', marginTop: '4rem', textAlign: 'center'}}>
               <h4 style={{color: '#fff', marginBottom: '1rem', fontSize: '1.2rem'}}>Compile native APKs in 10 minutes.</h4>
               <Link href="/app" className="btn btn-primary" style={{padding: '1rem 2rem'}}>Start Building Free</Link>
            </div>
         </div>
      </main>
    </>
  );
}
